### ISSUE TITLE
install on armbian doesnt work

### ISSUE THREAD

**Issue by Gibbz** [cockpit-project/cockpit-files#877]
Im trying to install this on armbian, however its not showing in the navigation bar. Im using armbian trixie on my orangepi4lts arm board.  
Im using the following method to install.
```
wget -c https://github.com/cockpit-project/cockpit-files/releases/download/13/cockpit-files-13.tar.xz
sudo tar xf cockpit-files-13.tar.xz -C /usr/share/cockpit
```

**Comment by Gibbz** [comment]
ok im trying to build from git now instead....

from the git folder i get the following build error:
```
> make
make package-lock.json && NODE_ENV= ./build.js
make[1]: Entering directory '/home/pi/cockpit-files'
tools/node-modules make_package_lock_json
make[1]: Leaving directory '/home/pi/cockpit-files'

node:internal/modules/run_main:128
    triggerUncaughtException(
    ^
Error [TransformError]: 
You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "@esbuild/linux-x64" package is present but this platform
needs the "@esbuild/linux-arm64" package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying "node_modules"
into a Docker image that runs Linux, or by copying "node_modules" between
Windows and WSL environments.

If you are installing with npm, you can try not copying the "node_modules"
directory when you copy the files over, and running "npm ci" or "npm install"
on the destination platform after the copy. Or you could consider using yarn
instead of npm which has built-in support for installing a package on multiple
platforms simultaneously.

If you are installing with yarn, you can try listing both this platform and the
other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.

    at generateBinPath (/home/pi/cockpit-files/node_modules/tsx/node_modules/esbuild/lib/main.js:1741:17)
    at esbuildCommandAndArgs (/home/pi/cockpit-files/node_modules/tsx/node_modules/esbuild/lib/main.js:1822:33)
    at ensureServiceIsRunning (/home/pi/cockpit-files/node_modules/tsx/node_modules/esbuild/lib/main.js:1979:25)
    at transform (/home/pi/cockpit-files/node_modules/tsx/node_modules/esbuild/lib/main.js:1880:37)
    at file:///home/pi/cockpit-files/node_modules/tsx/dist/index-DlKgSVBb.mjs:16:2755
    at applyTransformers (file:///home/pi/cockpit-files/node_modules/tsx/dist/index-DlKgSVBb.mjs:16:1266)
    at transform (file:///home/pi/cockpit-files/node_modules/tsx/dist/index-DlKgSVBb.mjs:16:2702)
    at load (file:///home/pi/cockpit-files/node_modules/tsx/dist/esm/index.mjs?1734327563390:2:2245)
    at async nextLoad (node:internal/modules/esm/hooks:868:22)
    at async Hooks.load (node:internal/modules/esm/hooks:451:20)

Node.js v20.18.1
make: *** [Makefile:92: dist/manifest.json] Error 1

```

**Comment by jelly** [comment]
> Im trying to install this on armbian, however its not showing in the navigation bar. Im using armbian trixie on my orangepi4lts arm board. Im using the following method to install.
> 
> ```
> wget -c https://github.com/cockpit-project/cockpit-files/releases/download/13/cockpit-files-13.tar.xz
> sudo tar xf cockpit-files-13.tar.xz -C /usr/share/cockpit
> ```

This is the preferred solution but please drop it into /usr/local/share/cockpit/ but you want to `mv` the dist folder to a directory called `files`. So

```
sudo mkdir -p /usr/share/local/cockpit/files
sudo tar xf cockpit-files-13.tar.xz -C /tmp/
mv /tmp/cockpit-files/dist /usr/share/local/cockpit/files 
```

**Comment by Gibbz** [comment]
Great thanks! got it working with the following:

```
cd $HOME
wget -c https://github.com/cockpit-project/cockpit-files/releases/download/13/cockpit-files-13.tar.xz
sudo tar xf cockpit-files-13.tar.xz -C /tmp/
sudo mkdir -p /usr/share/cockpit/files
sudo mv /tmp/cockpit-files/dist/* /usr/share/cockpit/files
```
